# Generated by Django 2.2 on 2019-04-18 11:02

import books.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=books.models.get_image_path)),
                ('listed_date', models.DateTimeField(default=datetime.datetime(2019, 4, 18, 11, 2, 15, 419272, tzinfo=utc))),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to='accounts.User')),
            ],
        ),
    ]
