# Generated by Django 2.2 on 2019-04-18 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='listed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 11, 3, 5, 818442, tzinfo=utc)),
        ),
    ]
