# Generated by Django 2.2 on 2019-04-18 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190418_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='listed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 11, 29, 14, 925732, tzinfo=utc)),
        ),
    ]
