# Generated by Django 2.2 on 2019-04-18 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190418_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='listed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 12, 57, 36, 509052, tzinfo=utc)),
        ),
    ]
