# Generated by Django 2.2.2 on 2019-06-19 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190418_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='listed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 10, 35, 55, 650702, tzinfo=utc)),
        ),
    ]
